---
language: python

before_install:
  - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-daily
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y freecad freecad-doc
  - gcc --version
  - g++ --version
  - python ./setup.py install
  - pip install coverage
  - pip install coveralls
  - pip install Sphinx==1.3.2
  - pip install travis-sphinx

script:
  - coverage run --source=cadquery ./runtests.py
  - travis-sphinx --nowarn --source=doc build

after_success:
  - coveralls
  - travis-sphinx deploy
  
branches:
  except:
    - pythonocc
    - 2_0_branch
